### ISSUE TITLE
Missing some files and variable 'alpha'

### ISSUE THREAD

**Issue by tingnim** [UCSD-AI4H/COVID-CT#10]
Hello, when i run the code 'CT_predict', a error occurred: alpha doesn't exist and i found this txt also doesn't exist.
`f = open('COVID-CT/model_result/DenseNet_{}.txt'.format(alpha), 'a+')`

Thanks for providing images again!

**Comment by jkooy** [comment]
This file is just used to print out the result. You can change it to any name you want.
The alpha is in line 220 of the script provided. 
Thanks.
