### ISSUE TITLE
Data split issue: should be patient level

### ISSUE THREAD

**Issue by HankUiECE** [UCSD-AI4H/COVID-CT#11]
It seems that the data split is with image-level, which means slices from the same patient could come to tran/test/val. This will bring some data-leakage problem. It is more reasonable to split in the patient level so that images from same patient cannot be assigned to different set(train/test/val)

**Comment by jkooy** [comment]
It is in patient-level, you can refer to the Metainfo and our datasplit txt.  In COVID patients 1-130 are splitted into train, 131-162 into val, and 163-216 into test.

**Comment by HankUiECE** [comment]
> It is in patient-level, you can refer to the Metainfo and our datasplit txt. In COVID patients 1-130 are splitted into train, 131-162 into val, and 163-216 into test.

Thanks! That makes sense I take a look at datasplit txt file and it seems 'p23' appears in both train/val/test. I will go through the Metainfo!
