### ISSUE TITLE
Please consult a radiologist regarding these issues

### ISSUE THREAD

**Issue by pcicales** [UCSD-AI4H/COVID-CT#13]
Hello,

Thank you for contributing to research revolving around COVID-19. Your data set is very valuable. 

I am not a physician, but upon consulting with collaborators it appears that the following issues should be addressed.

1) Soft tissue scans appear to be unpopular for this kind of application.
2) It appears that some cases of viral pneumonia are present in the control set. These will have similar (if not identical) manifestations to COVID-19.

Thank you again.

**Comment by Fischer19** [comment]
Thank you for the comments.
We do have contact with some radiologists and we will come up with a guideline on how to utilize our dataset.

**Comment by pcicales** [comment]
Thank you very much. Looking forward to working with your data!
