### ISSUE TITLE
Updata Code

### ISSUE THREAD

**Issue by huangjt001** [UCSD-AI4H/COVID-CT#14]
Hello,

Thank you for your data set .It is very valuable.

I am a graduate student, I clone your zip .But there is bug in code.
So I want a new updated code. My email 522421324@qq.com

Thank you again.

**Comment by jkooy** [comment]
Emailed you. We may open source a series of new code and pre-trained models in another repo in a few days. Thanks for your interests in our work.

**Comment by huangjt001** [comment]
Thank you very much for your help！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jkooy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午3:02
收件人:&nbsp;"UCSD-AI4H/COVID-CT"<COVID-CT@noreply.github.com&gt;;
抄送:&nbsp;"剑气伤人"<522421324@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [UCSD-AI4H/COVID-CT] Updata Code (#14)





 
Emailed you. We may open source a series of new code and pre-trained models in another repo in a few days. Thanks for your interests in our work.

**Comment by jixiaotong** [comment]
Hi, its very kind of you for the data and codes.
Bit I also suffer from some problem in the codes，maybe there are some bugs,
May I have the newest update of your code please?
My email is (xiaotong.ji@human.ait.kyushu-u.ac.jp)
Thank you very much!

**Comment by UCSD-AI4H** [comment]
> Hi, its very kind of you for the data and codes.
> Bit I also suffer from some problem in the codes，maybe there are some bugs,
> May I have the newest update of your code please?
> My email is ([xiaotong.ji@human.ait.kyushu-u.ac.jp](mailto:xiaotong.ji@human.ait.kyushu-u.ac.jp))
> Thank you very much!

Can you put it clear what bugs you encountered? The latest code has been put on in our repo along with the pretrained model. Plz have a look if you need.

**Comment by jkooy** [comment]
> Hi, its very kind of you for the data and codes.
> Bit I also suffer from some problem in the codes，maybe there are some bugs,
> May I have the newest update of your code please?
> My email is ([xiaotong.ji@human.ait.kyushu-u.ac.jp](mailto:xiaotong.ji@human.ait.kyushu-u.ac.jp))
> Thank you very much!

Can you put it clear what bugs you encountered? The latest code has been put on in our repo along with the pretrained model. Plz have a look if you need. I will be working on a readme file these days. Thanks for your interest.

**Comment by huangjt001** [comment]
Hi,
&nbsp; &nbsp; The last file you sent me,（train.py）,there are one file missed. It is 'utils'. Could give me a complete operational code so that I can run and test. I want to run in this set by your code. I follow your "read me", but there isn't work. You are updating a few code. I'm&nbsp;confused now. &nbsp;I am not writing paper now. So I'm not going to infringe on your interests and results. Thank you again！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jkooy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 凌晨0:39
收件人:&nbsp;"UCSD-AI4H/COVID-CT"<COVID-CT@noreply.github.com&gt;;
抄送:&nbsp;"剑气伤人"<522421324@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [UCSD-AI4H/COVID-CT] Updata Code (#14)





  
Hi, its very kind of you for the data and codes.
 Bit I also suffer from some problem in the codes，maybe there are some bugs,
 May I have the newest update of your code please?
 My email is (xiaotong.ji@human.ait.kyushu-u.ac.jp)
 Thank you very much!
  
Can you put it clear what bugs you encountered? The latest code has been put on in our repo along with the pretrained model. Plz have a look if you need. I will be working on a readme file these days. Thanks for your interest.

**Comment by jkooy** [comment]
The code is updated in Self-Trans/CT_predict-efficient-pretrain.ipynb. The repo contains the MoCo code to pretrain. You can disregard these files and train from scratch. The only thing you need to do is to modify the data path to which you store the image and split txt file, and the model path in the code.
