### ISSUE TITLE
A error of the baseline method densenet169

### ISSUE THREAD

**Issue by xifengqianyu** [UCSD-AI4H/COVID-CT#16]
Excuse me~ when I run the baseline methods, I met the following question:
RuntimeError: Given groups=1, weight of size 32 3 3 3, expected input[10, 1, 225, 225] to have 3 channels, but got 1 channels instead.

I have no idea, can you help me?

**Comment by jkooy** [comment]
Our input is the same in all 3 channels. 
You can delete these two lines

              data = data[:, 0, :, :]
              data = data[:, None, :, :]

in line `201` in train function and 266 in `val` function. I left them becasue some models require input channel to be 1.
