### ISSUE TITLE
COVID-19 patient data for research

### ISSUE THREAD

**Issue by jeremykohn** [UCSD-AI4H/COVID-CT#18]
There's a new dataset that HM Hospitales in Spain is sharing with qualified researchers, consisting of anonymized medical records from COVID-19 patients:

https://www.hmhospitales.com/prensa/notas-de-prensa/comunicado-covid-data-save-lives

> From April, 25th onwards, the 'COVID DATA SAVE LIVES' contents will be distributed online, free of cost and other access barriers to worldwide health care institutions, universities, and scientific organizations...

> To access this initiative, it is mandatory to submit an application via e-mail to coviddatasavelives@hmhospitales.com which will be assessed by the HM Hospitales Data Science Commission and, where appropriate, reviewed by the HM Hospitales Clinical Research Ethics Committee.

**Comment by Fischer19** [comment]
Hi Jeremy,
Thanks for the information! We will take a look at it.

**Comment by jkooy** [comment]
Thanks for your information. We applied for this dataset and looked at it, what they got are xray images but not CT.
