### ISSUE TITLE
NonCOVID-CT-Images.zip is missing

### ISSUE THREAD

**Issue by saimunur** [UCSD-AI4H/COVID-CT#2]
Hi! Do you have any plan to upload NonCOVID-CT-Images.zip? Currently, only COVID-CT-Images.zip is available! Kindly advise. Thanks

**Comment by pengtaoxie** [comment]
Hi Saimunur,
We are preparing for a non-covid CT image dataset.
Will upload soon.

Best,
Pengtao

**Comment by RoshanTanisha** [comment]
There are images available here: I took the normal CT images from here only.
https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia

**Comment by pengtaoxie** [comment]
Thank you, Tanisha.
We will look into it.

Best,
Pengtao

**Comment by alexlorenzo** [comment]
Hello, 

Finally for NonCOVID images did you take the kaggle datasets? Could you confirm?

**Comment by UCSD-AI4H** [comment]
> Hello,
> 
> Finally for NonCOVID images did you take the kaggle datasets? Could you confirm?

Hi alexlorenzo, we are still preparing NON COVID images. The kaggele datasets only contain xray images. We will release updated NonCOVID images soon.
