### ISSUE TITLE
About the format of the submission file for COVID-19 CT competition

### ISSUE THREAD

**Issue by czifan** [UCSD-AI4H/COVID-CT#21]
Thank you very much for providing the dataset and baseline model! I am participating in the COVID-19 CT competition (https://covid-ct.grand-challenge.org/), but I cannot find the format of the submission file on the competition page. Could you provide a sample submission file or describe the format of the submission file in detail?

**Comment by jkooy** [comment]
Hi, thanks for your participation. 
Please refer to this page https://covid-ct.grand-challenge.org/Challenge-Rules/
