### ISSUE TITLE
I didn't get the same result by your best Self-Trans.pt model

### ISSUE THREAD

**Issue by LXYTSOS** [UCSD-AI4H/COVID-CT#23]
according to your readme file, your result was F1: 0.85，Accuracy: 0.86，AUC: 0.94，but mine was F1:0.74, Accuracy:0.77, AUC:0.88. Should I use the Self-Trans.pt as a pretrained model and fine tune on it?

**Comment by jkooy** [comment]
Nope, the model has already been fine-tuned on our dataset. If you follow our script and use the same data split, you should get this performance.

**Comment by LXYTSOS** [comment]
That's weird, because I found out that the output shape of Self-Trans.pt is 1000, this means this model is a 1000 classes classifier not a binary classifier. But never mind, I load the model and change the output shape from 1000 to 2 and retrain it, now I'm getting the result close to yours.

**Comment by jkooy** [comment]
> That's weird, because I found out that the output shape of Self-Trans.pt is 1000, this means this model is a 1000 classes classifier not a binary classifier. But never mind, I load the model and change the output shape from 1000 to 2 and retrain it, now I'm getting the result close to yours.

That is because the Self-Trans model is first pretrained on the ImageNet. It doesn't affect the results as it is finally fine-tuned on the CT dataset with two classes.

**Comment by LXYTSOS** [comment]
I choose efficientnet to train on LUNA  by moco, how can I reload the weights to the EfficientNet defined in efficientnet_pytorch when train on COVID-CT, the keys don't match, I don't know how to load the keys into the right place.

**Comment by jkooy** [comment]
> I choose efficientnet to train on LUNA by moco, how can I reload the weights to the EfficientNet defined in efficientnet_pytorch when train on COVID-CT, the keys don't match, I don't know how to load the keys into the right place.

You only need the encoder from MoCo. You can either write regular expression or simple if..else.. statements. There are some examples in the ipynb file, about [31].

**Comment by LXYTSOS** [comment]
Thanks, and how to generate the gradcam.png under baseline model exactly?

**Comment by jchilela** [comment]
Hello guys, we are trying to reproduce your work. It seems that some txt files are missing. We are seeing this error: 
FileNotFoundError                         
`FileNotFoundError                         Traceback (most recent call last)


<ipython-input-18-b71253aaae34> in <module>()
    156                               txt_COVID='new_data/newtxt/train.txt',
    157                               txt_NonCOVID='/content/drive/My Drive/Covid_CT/Content2/CovidCTNew/Data-split/COVID/trainCT_NonCOVID.txt',
--> 158                               transform= train_transformer)
    159     valset = CovidCTDataset(root_dir='new_data/4.4_image',
    160                               txt_COVID='new_data/newtxt/val.txt',
`
