### ISSUE TITLE
FIilenotfound error in the File: DenseNet_predict.py

### ISSUE THREAD

**Issue by jchilela** [UCSD-AI4H/COVID-CT#28]
Guys we are trying to run your code. The problem is this error below. I think your github is missing files. Can you please give us a workaround?: 

`FileNotFoundError                         
Traceback (most recent call last)
<ipython-input-18-b71253aaae34> in <module>()
    156                               txt_COVID='new_data/newtxt/train.txt',
    157                               txt_NonCOVID='/content/drive/My Drive/Covid_CT/Content2/CovidCTNew/Data-split/COVID/trainCT_NonCOVID.txt',
--> 158                               transform= train_transformer)
    159     valset = CovidCTDataset(root_dir='new_data/4.4_image',
    160                               txt_COVID='new_data/newtxt/val.txt',
`

**Comment by jkooy** [comment]
The data split files are in the Data-split repo. You need to change your path. Please see the readme.
