### ISSUE TITLE
You cannot train a classifier on these images 

### ISSUE THREAD

**Issue by LuisBlanche** [UCSD-AI4H/COVID-CT#3]
The images with COVID come from various sources and most of them are annotated whereas the NON COVID images are all very homogeneous. If you train a classifier on theses images, you will build an "Image source classifier" , not a "COVID classifier" 

![image](https://user-images.githubusercontent.com/18741447/78337273-069ece80-7591-11ea-9b82-d8c790aa77cf.png)

**Comment by UCSD-AI4H** [comment]
Sorry, we are still preparing NON COVID images that are homogeneous with COVID images. We will release them very soon.

**Comment by LuisBlanche** [comment]
Great, thank you for providing this data anyway !

**Comment by huangchaoxing** [comment]
> The images with COVID come from various sources and most of them are annotated whereas the NON COVID images are all very homogeneous. If you train a classifier on theses images, you will build an "Image source classifier" , not a "COVID classifier"
> 
> ![image](https://user-images.githubusercontent.com/18741447/78337273-069ece80-7591-11ea-9b82-d8c790aa77cf.png)

I suppose  they only include the Positive image in the file. Where is the "non-COVID" image you display comes from ? Is it from the kaggle link ?

**Comment by LuisBlanche** [comment]
@huangchaoxing , no the non-COVID images are from this repo as well. Maybe an interesting idea would be to diversify these images , maybe by getting some scans of other diseases like classic pneumonia or lung cancer ?  [Here is a dataset with lung CT scans on kaggle : ](https://www.kaggle.com/kmader/finding-lungs-in-ct-data)

**Comment by pengtaoxie** [comment]
Dear Chaoxing,
We are preparing the negative images and will upload soon.

Best,
Pengtao

**Comment by pengtaoxie** [comment]
Dear Luis,
Thanks for pointing out this link.
We will look into it.

Best,
Pengtao

**Comment by ayooshkathuria** [comment]
@huangchaoxing The repo had negative images, which were later removed may be due to concerns raised by @LuisBlanche. In case you need to access the negative image, you should check out to commit `5f3a1bae40a1f31804e6e2822b23bff6ca49ad47`

**Comment by Tzeny** [comment]
Any news on this issue?

**Comment by jkooy** [comment]
> Any news on this issue?

Hi Tzeny, both COVID images and NonCOVID images have been updated. We also released metafiles for you to refer. You can check them.

**Comment by Tzeny** [comment]
Thank you!

**Comment by LuisBlanche** [comment]
We have shared you dataset on Kaggle. You can tell me if the copyright info is right [https://www.kaggle.com/luisblanche/covidct/kernels](https://www.kaggle.com/luisblanche/covidct/kernels)
Thanks!
