### ISSUE TITLE
DenseNet Questions

### ISSUE THREAD

**Issue by saja1994** [UCSD-AI4H/COVID-CT#31]
Thank you for your effort. Please I have two questions.
1. What is the required total number of epochs to get the reported results? Because in DenseNet_predict.py file I noticed that there are 3000 epochs which is extremely high!! 
2. In the DenseNet_predict.py, did you tuned the networks pretrained weights or you are using them as is?
Thanks

**Comment by jkooy** [comment]
Hello, 
1. There is another similar question posted before, the number is the maximum. Don't need that much, when you observe the loss on val set doesn't reduce you can stop it. 
2. The weights are tuned.
