### ISSUE TITLE
How to Run your code? Please give a workflow. 

### ISSUE THREAD

**Issue by anirban1513** [UCSD-AI4H/COVID-CT#32]

**Comment by jkooy** [comment]
You can refer to `README` in `baseline methods`. Most problems have also been covered in previous Issues.

**Comment by anirban1513** [comment]
root_dir='new_data/4.4_image'   

Where should I put the path for the COVID Image and Non-Covid Image folder? What do this root_dir means in densenet_predict.py? Does this root_dir have to contain both the  Covid and Non Covid Images?

**Comment by anirban1513** [comment]
I ran your DenseNet_predict.py first.... But It shows an error... 

No such file or directory: 'model_result/efficientNet-b0.txt'
