### ISSUE TITLE
How do you select the model to use for the test data?

### ISSUE THREAD

**Issue by yangzez** [UCSD-AI4H/COVID-CT#33]
Hi,

I am not sure how do you select the model to use for the test data. It seems to me in your code you did not use the information from the validation dataset to choose the model to use on the test data. I also did not observe any early stopping criteria being used. Is that true? If it is, how do you select the model and what is the purpose of the validation dataset?

Thanks,
Yangze

**Comment by jkooy** [comment]
The code is simple and the early stopping is not implemented here. The model is selected when the loss observed on val set doesn't reduce any more.
