### ISSUE TITLE
How to download dataset?

### ISSUE THREAD

**Issue by kalelpark** [UCSD-AI4H/COVID-CT#43]
How to download dataset?

**Comment by chenchongpal** [comment]
您的邮件已收到，谢谢。

**Comment by kalelpark** [comment]
> 您的邮件已收到，谢谢。

用邮件发送就可以了吗？
能告诉我邮件要发到哪里吗？

**Comment by kalelpark** [comment]
能把Dataset用邮件发给我吗？

2022년 12월 29일 (목) 오후 12:28, chenchongpal ***@***.***>님이 작성:
