### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by ncovgt2020** [UCSD-AI4H/COVID-CT#6]
Hi,

I have been spending some hours every other day to check for papers containing CT or Xray images of COVID-19 patients. Are you accepting contributions in any way?  In the case of the [covid-19 x-ray collection project](https://github.com/ieee8023/covid-chestxray-dataset), they keep a list of already collected papers, and one can inform of not-yet-collected papers in the issues section. Please advice us on how to contribute with papers containing CT images that you might have not yet included in your dataset.

**Comment by Fischer19** [comment]
Hi,
Thanks for the comment,  keeping a list of collected papers is a good idea! We will come up with a plan for contribution and post it on the front page soon.
