### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by ncovgt2020** [UCSD-AI4H/COVID-CT#7]
Hi,

Thank you for the for the effort of putting this dataset together.

Probably you have checked the [metadata that is being collected for the covid x-ray dataset project](https://github.com/ieee8023/covid-chestxray-dataset/blob/master/metadata.csv). I would suggest on collecting a more specific and detailed metadata on each scan, as in the mentioned project, so that better insights can be obtained from the dataset.

Thanks!

**Comment by pengtaoxie** [comment]
Thank you for the suggestion! We will try to add much meta info as available.
