### ISSUE TITLE
getting 

### ISSUE THREAD

**Issue by james-workig** [UCSD-AI4H/COVID-CT#8]
i cloned, then i install everything, but when i try to run "python CT_predict.py"  i am getting following error:  No such file or directory: 'COVID-CT/train_set'"  can you please rell, what chnges i need to made after clone.

yes thanks for providing ct images.
Thanks

**Comment by pengtaoxie** [comment]
Thanks for the feedback. We will update the code soon.

**Comment by james-workig** [comment]
@pengtaoxie  but can you tell how to run script, i am running simply CT_predict.py, should i need to make some other chnges??

**Comment by pengtaoxie** [comment]
This code is a bit outdated.
We will upload a new version soon.
Can you check it later on?

**Comment by james-workig** [comment]
it will be good if you update soon,Thanks
