### ISSUE TITLE
Incorrect file names in the val datasplit file valCT_COVID.txt

### ISSUE THREAD

**Issue by ayooshkathuria** [UCSD-AI4H/COVID-CT#9]
For example, in the file `Data-Splits/COVID/valCT_COVID.txt`, there is a file called `2020.03.16.20036145-p19-128-4.png`. 

However, in the image processed folder, `Image-Processed/COVID`, the file is saved using a JPEG extension as `2020.03.16.20036145-p19-128-4.jpeg` . 

There are some other files like this too such as `Images-processed/CT_COVID/2020.03.18.20038125-p15-54-2.png`. I got over this by making sure all files had the same extension but please fix this.

**Comment by Kingpopen** [comment]
oh， the same with you!

**Comment by Fischer19** [comment]
The issue has been fixed. Thank you for pointing it out.

**Comment by ayooshkathuria** [comment]
Again, the files 
```
2020.03.12.20034686-p17-91-1.png
2020.03.12.20034686-p17-91-2.png
```
are there in `testCT_COVID.txt`, but they have been deleted in the zip files.

**Comment by Fischer19** [comment]
It's fixed. We double-checked the data split files, there should be no error now.
Thanks again for pointing it out.
